In [1]:
from numba import jit
from numpy import arange

# jit decorator tells Numba to compile this function.
# jit은 Numba에게 해당 함수를 컴파일 할 것을 알려준다.
# The argument types will be inferred by Numba when function is called.
# 함수 호출 단계에서 Numba에 의해 argument의 type이 정해진다.
@jit
def sum2d(arr): # jit이 Numba에게 컴파일을 요청할 함수
    M, N = arr.shape
    result = 0.0
    for i in range(M):
        for j in range(N):
            result += arr[i,j]
    return result

a = arange(9).reshape(3,3)
print(sum2d(a)) # jit에 의해 지정된 함수인 sum2d()의 인자 a의 type은 Numba가 결정한다.

36.0


In [4]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3, 3)

In [7]:
import numpy as np
from numba import guvectorize

@guvectorize(['void(float64[:], intp[:], float64[:])'], '(n),()->(n)')
def move_mean(a, window_arr, out):
    window_width = window_arr[0]
    asum = 0.0
    count = 0
    for i in range(window_width):
        asum += a[i]
        count += 1
        out[i] = asum / count
    for i in range(window_width, len(a)):
        asum += a[i] - a[i - window_width]
        out[i] = asum / count

arr = np.arange(20, dtype=np.float64).reshape(2, 10)
print(arr)
print(move_mean(arr, 3))

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]]
[[  0.    0.5   1.    2.    3.    4.    5.    6.    7.    8. ]
 [ 10.   10.5  11.   12.   13.   14.   15.   16.   17.   18. ]]
