In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = [5,6,7,8,9]

In [5]:
type(arr2)

list

In [6]:
arr3 = np.array(arr2)

In [7]:
type(arr3)

numpy.ndarray

In [8]:
arr2

[5, 6, 7, 8, 9]

In [9]:
arr3

array([5, 6, 7, 8, 9])

In [10]:
arr4 = [[1,2,3,4,5],[5,6,7,8,9]]
arr5 = np.array(arr4)

In [11]:
arr5

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [13]:
arr5.shape
type(arr5.shape)

tuple

In [14]:
arr5.shape[0]

2

In [15]:
a = (1,2)
a[0] # It's possible to access using index at Tuple.

1

In [17]:
arr5.shape[1]

5

In [18]:
arr5.dtype

dtype('int64')

In [19]:
arr6 = [1,2,3,4,5,6]

In [20]:
type(arr6)

list

In [21]:
arr7 = np.asarray(arr6)

In [22]:
arr7

array([1, 2, 3, 4, 5, 6])

In [23]:
type(arr7)

numpy.ndarray

In [24]:
b = np.array([1,2])

In [25]:
type(b)

numpy.ndarray

In [26]:
b

array([1, 2])

In [30]:
np.array(b) is b

False

In [31]:
type(np.array(b))

numpy.ndarray

In [32]:
np.asarray(b) is np.array(b)

False

In [38]:
a = [1,2,3,4,5]
b = np.array(a)
a[2] = 100
print(type(a))
print(a)
print(type(b))
print(b)
print(a)

<class 'list'>
[1, 2, 100, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
[1, 2, 100, 4, 5]


In [39]:
a = [1,2,3,4,5]
b = np.asarray(a)
a[2] = 100
print(type(a))
print(a)
print(type(b))
print(b)

<class 'list'>
[1, 2, 100, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [41]:
A = np.matrix(np.ones((3,3)))

In [42]:
A

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [43]:
type(A)

numpy.matrixlib.defmatrix.matrix

In [47]:
np.array(A)[2]=2 # The elements where are at the end

In [48]:
A

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [49]:
np.asarray(A)[2]=2

In [50]:
A

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 2.,  2.,  2.]])

In [51]:
d = [6,7,8,9,10]

In [52]:
e = np.asfarray(d)
print(e)

[  6.   7.   8.   9.  10.]


In [53]:
e = [11,12,13,14,15]

In [54]:
np.asarray_chkfinite(e, dtype=float)

array([ 11.,  12.,  13.,  14.,  15.])

In [55]:
e_2 = [11,12,13,np.nan, 15]

In [56]:
np.asarray_chkfinite(e_2, dtype=float)

ValueError: array must not contain infs or NaNs

In [57]:
e_3 = [11,12,13,14, np.inf]

In [58]:
e_3

[11, 12, 13, 14, inf]

In [59]:
np.asarray_chkfinite(e_3, dtype=float)

ValueError: array must not contain infs or NaNs

In [62]:
np.zeros(5, dtype='uint8')

array([0, 0, 0, 0, 0], dtype=uint8)

In [64]:
np.ones(10, dtype="int64")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [71]:
np.empty([20], dtype="int8")

array([   0,    0,    0,    0,    0,    0,    0,  -32,  -59,    7,   96,
       -118,   -1,    7,    0,  112,    2,    0,    0,    0], dtype=int8)

In [72]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [74]:
np.ones((3,5,1))

array([[[ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.]],

       [[ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.]],

       [[ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.]]])

In [75]:
np.empty((3,9))

array([[ -2.68156159e+154,  -2.68156159e+154,   1.18575755e-322,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.16318369e-028,   1.32813920e-075,  -2.68156159e+154,
         -2.68156159e+154,   6.59356312e-066,   5.04621361e+180],
       [  8.37170571e-144,   1.69637266e+190,   5.01163206e+217,
          5.49419094e-143,   1.50008929e+248,   3.75598257e+199,
          6.11970980e+169,   9.42347829e-047,   6.12145498e+169]])

In [79]:
f = np.arange(10)

In [77]:
np.arange(100,1000,2)

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306,
       308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332,
       334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358,
       360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384,
       386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410,
       412, 414, 416, 418, 420, 422, 424, 426, 428, 430, 432, 434, 436,
       438, 440, 442, 444, 446, 448, 450, 452, 454, 456, 458, 46

In [80]:
f_2_5 = f.reshape(2,5)

In [81]:
f_2_5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
a = np.zeros_like(np.arange(0,10).reshape(5,2))

In [88]:
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [86]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [89]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [90]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [91]:
np.identity(5) is np.eye(5)

False

In [98]:
print(np.eye(3))
print(np.eye(3, k=0))
print(np.eye(3, k=1))
print(np.eye(3, k=2))
print(np.eye(3, k=3))
print(np.eye(3, k=-1))
print(np.eye(3, k=-2))
print(np.eye(3, k=-3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [101]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [102]:
import pandas as pd

In [118]:
csv_test = pd.read_csv("/Users/do-hyungkwon/Downloads/test_csv_file.csv", sep=",")

In [119]:
csv_test

ID LAST_NAME  AGE
0   1       KIM   30
1   2      CHOI   25
2   3       LEE   41
3   4      PARK   19
4   5       LIM   36

In [105]:
type(csv_test)

pandas.core.frame.DataFrame

In [120]:
csv_test.shape

(5, 3)

In [109]:
np.empty((5,5)).shape

(5, 5)

In [126]:
test_file = pd.read_csv("/Users/do-hyungkwon/Downloads/test_text_file.txt")

In [127]:
print(test_file)
print(test_file.shape)

   ID|A|B|C|D
0  C1|1|2|3|4
1  C2|5|6|7|8
2  C3|1|3|5|7
(3, 1)


In [128]:
test_file = pd.read_csv("/Users/do-hyungkwon/Downloads/test_text_file.txt", sep="|")

In [129]:
print(test_file)
print(test_file.shape)

   ID  A  B  C  D
0  C1  1  2  3  4
1  C2  5  6  7  8
2  C3  1  3  5  7
(3, 5)


In [115]:
test_file.shape

(3, 5)