In [346]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from scipy.misc import imread
import numpy as np
import os
import tensorflow as tf
import glob
import random
import shutil 

DATASET_PATH = "./dataset"
kinds = ["train", "validation", "test"]
train_img = np.array([], dtype="float32")
train_label = np.array([], dtype="int8")
validation_img = np.array([], dtype="float32")
validation_label = np.array([], dtype="int8")
test_img = np.array([], dtype="float32")
test_label = np.array([], dtype="int8")


def return_all_filename(category_name): 
    # 디렉토리 상의 모든 파일의 이름 부분만 긁어와서 리스트로 반환
    # 파일들을 랜덤하게 불러올 필요가 있는 영역...
    # extract every file's name in the directory.
    full_path = DATASET_PATH + '/' + category_name + '/' + '*.png'
    image_filenames = glob.glob(full_path)
    filename = []
    label = []
    for image_filename in image_filenames:
        filename.append(image_filename.split("/")[3])
        label.append(image_filename.split("/")[3].split("-")[0])
    return (label, filename)

def image_display(kind, filename):
    image_data = imread(DATASET_PATH + '/' + kind + '/' + filename)
    
    
def data_processing_about_train(idx, kind):
    for i in range(idx):
        global train_img
        global train_label
        
        (labels, filenames) = return_all_filename(kind)
        random_value = random.randrange(0, len(filenames))
        filename = filenames[random_value]
        label = _change_one_hot_label(labels[random_value])
#         label = labels[random_value]
#         image_display(kinds, filename)
        full_path = (DATASET_PATH + '/' + kind + '/' + filename)
        image = imread(full_path)
        image = image.reshape(640*480*3)/255.0
        train_img = np.append(train_img, image)
        train_label = np.append(train_label, label)
        # file move
        print(len(filenames))
        print(filename)
        src = './dataset' + '/' + kind + '/'
        dir = './dataset' + '/' + 'tmp' + '/' + kind + '/'
        shutil.move(src + filename, dir + filename)


def _change_one_hot_label(labels):
    idx = len(labels)
    for i in range(idx):
        labels[i] = int(labels[i])
        
# #     T = np.zeros((idx, 3))
#     for index, row in enumerate(T):
    row[labels[index]] = 1

#     return T
    return row




(label_train, filename_train) = return_all_filename("train")
(label_validation, filename_validation) = return_all_filename("validation")
(label_test, filename_test) = return_all_filename("test")

idx = len(filename_train)
train_img = np.array([], dtype="float32")
data_processing(idx, "train")

train_img = train_img.reshape(idx, 921600)
train_label = train_label.reshape(idx, 3)



# idx = len(filename_validation)
# data_processing(idx, "validation")
# idx = len(filename_test)
# data_processing(idx, "test")




# image_data_train = imread("./RP_data_4/critical/critical-20170712_120329_321515.png")
# image_data2 = imread("./RP_data_4/critical/critical-20170712_121250_575724.png")
# (width, height, channel) = (image_data.shape)
# print(width, height, channel)
# print()
# print("image_data's SHAPE: ", image_data.shape)
# print("image_data's type: ", (type(image_data)))
# print()
# image_data = image_data.reshape(640*480*3)
# print("image_data's SHAPE: ", image_data.shape)
# print("image_data's type: ",(type(image_data)))
# print()

# train_img = np.append(train_img, [image_data])
# train_img = np.append(train_img, [image_data2])

# print(train_img)
# print(type(train_img))
# print(train_img.shape)

18
0-0011_973397.png
17
2-080013_785409.png
16
2-080020_786869.png
15
0-0020_105321.png
14
1-0170713_075251_075570.png
13
0-0029_544215.png
12
1-0170713_081909_516990.png
11
0-0014_039206.png
10
1-0170713_081904_388570.png
9
1-0170713_082111_509382.png
8
0-0031_610631.png
7
1-0170713_081856_326451.png
6
2-075836_230652.png
5
2-080000_536460.png
4
2-080047_659311.png
3
0-0018_038956.png
2
2-080050_156757.png
1
0-0009_773482.png


ValueError: cannot reshape array of size 0 into shape (18,3)

In [339]:
print("train_img")
print(train_img)
print("train_img's Type: ", type(train_img))
print("train_img's Shape: ", train_img.shape)
print()
print("train_label")
print(train_label)
print("train_label's Type: ", type(train_label))
print("train_label's Shape: ", train_label.shape)
print()

train_img
[ 0.52941176  0.48627451  0.52156863 ...,  0.2         0.16470588
  0.15294118]
train_img's Type:  <class 'numpy.ndarray'>
train_img's Shape:  (25804800,)

train_label
[]
train_label's Type:  <class 'numpy.ndarray'>
train_label's Shape:  (0,)



In [342]:
print(train_label)

[]


In [306]:
(labels, filenames) = return_all_filename("train")
img_size = len(filenames)

train_data_test = train_img.reshape(17, 921600)
print(train_data_test.shape)

# train_label_test = train_label.reshape(17, 1)
print(train_label)

(17, 921600)
[]


In [128]:
train_data_test = train_data_test/255.0
print(train_data_test)
print(type(train_data_test))
print(train_data_test.shape)
# https://opensource.com/life/15/2/resize-images-python
# imgT = np.transpose(img, (2, 0, 1))
# print(imgT.shape)

[[ 0.71372551  0.56862748  0.61176473 ...,  0.34901962  0.34117648
   0.37254903]
 [ 0.69803923  0.54901963  0.627451   ...,  0.35686275  0.34117648
   0.36470589]]
<class 'numpy.ndarray'>
(2, 921600)


In [147]:
# realtime_caputure.py에서 찍힌 이미지들의 이름 바꾸기
# 맨 앞의 특정 문자열들을 지정한 후, 해당하는 이름을 갖는 모든 파일의 이름을 한 번에 바꿈
import os
def change_filenames(category):
    if not type(category) == type(""):
        print("please enter String..")
        return
    PATH = "./dataset/eval" + '/' + category + '/'
    for filename in os.listdir(PATH):
        if filename.startswith("NeuroSafe"):
            os.rename(PATH+filename[0:9]+filename[9:], PATH + category + filename[9:])
        elif filename.startswith("UnlabeledNeuroSafe"):
            os.rename(PATH+filename[0:18]+filename[18:], PATH + category + filename[18:])
change_filenames("warning")

In [313]:
# realtime_caputure.py에서 찍힌 이미지들의 이름 바꾸기
# 맨 앞의 특정 문자열들을 지정한 후, 해당하는 이름을 갖는 모든 파일의 이름을 한 번에 바꿈
import os
def change_filenames(category):
    if not type(category) == type(""):
        print("please enter String..")
        return
    PATH = "./dataset" + '/' + category + '/'
    for filename in os.listdir(PATH):
        if filename.startswith("warning"):
            os.rename(PATH+filename[0:9]+filename[9:], PATH + "1" + "-" + filename[9:])
        elif filename.startswith("normal"):
            os.rename(PATH+filename[0:18]+filename[18:], PATH + "0" + "-" + filename[18:])
        elif filename.startswith("critical"):
            os.rename(PATH+filename[0:18]+filename[18:], PATH + "2" + "-" + filename[18:])
change_filenames("train")
change_filenames("test")
change_filenames("validation")

In [56]:
if filename[]

In [65]:
import random
category = ["normal", "warning", "critical"]
for _ in range(10):
    print(category[random.randrange(0,3)])

warning
warning
warning
normal
warning
critical
normal
critical
warning
warning


In [68]:
category_name = "critical"
full_path = DATASET_PATH + '/' + category_name + '/' + '*.png'
print(full_path)
print(type(full_path))

./RP_data_3/critical/*.png
<class 'str'>


In [125]:
A = np.array([],dtype="uint8") 
B = np.array([],dtype="uint8")
for i in range(5): 
    A = np.append(A, i)
    B = np.append(B, A[i]+i)
print("A: ", A)
print("B: ", B)


print(type(A))

A:  [0 1 2 3 4]
B:  [0 2 4 6 8]
<class 'numpy.ndarray'>


In [137]:
DATASET_PATH = "./RP_data_4"
category = ["normal", "warning", "critical"]
# random.randrange(0,3)

def return_all_filename(category_name): 
    # 디렉토리 상의 모든 파일의 이름 부분만 긁어와서 리스트로 반환
    # extract every file's name in the directory.
    full_path = DATASET_PATH + '/' + category_name + '/' + '*.png'
    image_filenames = glob.glob(full_path)
    filename = []
    for image_filename in image_filenames:
        filename.append(image_filename.split("/")[3])
#     print(filename)
    return filename
len(return_all_filename("normal"))

150

In [150]:
# 디렉토리 내의 파일을 랜덤하게 부르는
idx = len(return_all_filename("train"))
def foo(idx):
    for _ in range(idx):
        print(category[random.randrange(0,3)])
foo(idx)

normal
normal
normal
critical
critical
normal
normal
warning
normal
critical
normal
warning
normal
normal
warning
warning
warning
warning
critical
normal
warning
normal
warning
warning
warning
normal
normal
critical
critical
normal
critical
critical
critical
critical
critical
warning
critical
normal
normal
critical
warning
warning
normal
normal
critical
warning
warning
critical
critical
critical
normal
critical
warning
normal
critical
normal
critical
warning
normal
warning
warning
warning
warning
critical
warning
normal
critical
critical
critical
warning
normal
warning
normal
normal
normal
warning
warning
warning
normal
normal
warning
critical
critical
warning
warning
warning
normal
warning
critical
critical
warning
critical
critical
warning
normal
normal
warning
critical
critical
critical
normal
normal
warning
critical
normal
normal
warning
warning
critical
normal
normal
normal
normal
normal
normal
critical
warning
warning
critical
normal
warning
warning
warning
warning
critical
warni

In [ ]:
def foo(idx):
        for _ in range(idx):
            print(category[random.randrange(0,3)])
    foo(idx)

In [151]:
import shutil 
# 학습이 끝난 파일은 다른 폴더로 옮겨지도록 한다.
filename = 'critical' 
src = './' 
dir = './output/' 
shutil.move(src + filename, dir + filename)


'./output/critical'

In [158]:
image_data = imread(DATASET_PATH + '/' + 'validation' + '/' + filename)

In [164]:
(label, filename) = return_all_filename("train")
print(len(label))
print(type(label))
for _ in range(len(label)):
    print(label[random.randrange(0,3)])

451
<class 'list'>
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical
critical


In [205]:
(tmp1, tmp2) = return_all_filename("validation")

In [202]:
print(type(tmp2[0]))

<class 'str'>


65
critical-20170720_070016_939494.png
64
critical-20170720_061139_651560.png
63
warning-20170717_133058_203451.png
62
warning-20170718_130254_806790.png
61
normal-20170712_113435_671032.png
60
critical-20170720_024548_322136.png
59
critical-20170719_131623_834129.png
58
warning-20170719_011812_290240.png
57
warning-20170716_055011_667088.png
56
critical-20170720_115755_465470.png
55
warning-20170716_114345_450605.png
54
warning-20170716_050749_419496.png
53
critical-20170713_084037_461946.png
52
normal-20170720_120015_972462.png
51
normal-20170712_113444_516786.png
50
critical-20170720_065905_690301.png
49
warning-20170720_115848_123163.png
48
critical-20170719_092030_454980.png
47
critical-20170720_021859_499500.png
46
warning-20170716_114429_261939.png
45
warning-20170717_115907_802730.png
44
warning-20170719_053240_723220.png
43
critical-20170716_040240_209826.png
42
warning-20170720_115937_179938.png
41
normal-20170720_110332_477701.png
40
normal-20170720_110420_369244.png
39
crit

In [184]:
print(len(tmp))
print(type(tmp[1]))
print(tmp[1][0])
print(tmp[0][0])
print(len(tmp2))

2
<class 'list'>
critical-20170712_120329_321515.png
critical
65


In [336]:
def file_move(idx, kind):
    for i in range(idx):
        (label, filenames) = return_all_filename(kind)
        filename = filenames[random.randrange(0, len(filenames))]
#         image_display(kinds, filename)
        full_path = (DATASET_PATH + '/' + kind + '/' + filename)
        image = imread(full_path)
        # file move
        print(len(filenames))
        print(filename)
        src = './dataset' + '/' + kind + '/'
        dir = './dataset' + '/' + 'tmp' + '/' + kind + '/'
        shutil.move(src + filename, dir + filename)

In [337]:
(label_train, filename_train) = return_all_filename("train")
(label_validation, filename_validation) = return_all_filename("validation")
(label_test, filename_test) = return_all_filename("test")

idx = len(filename_train)
file_move(idx, "train")
# idx = len(filename_validation)
# file_move(idx, "validation")
# idx = len(filename_test)
# file_move(idx, "test")

451
2-080248_840091.png
450
0-1420_712635.png
449
2-130540_211816.png
448
2-075755_496801.png
447
0-0020_105321.png
446
0-0613_848256.png
445
2-045850_271511.png
444
1-0170716_073748_504396.png
443
2-075759_733760.png
442
1-0170719_060257_026199.png
441
0-0616_181588.png
440
2-180352_448195.png
439
1-0170716_114448_696288.png
438
0-0156_462237.png
437
0-1017_381586.png
436
2-035411_940332.png
435
2-175002_668595.png
434
1-0170719_060308_144339.png
433
0-1414_375597.png
432
2-234258_815932.png
431
2-025530_649136.png
430
2-082718_101504.png
429
0-0641_742568.png
428
1-0170720_115940_046082.png
427
2-084027_275137.png
426
1-0170720_115907_819103.png
425
2-080013_785409.png
424
1-0170719_055914_669797.png
423
2-082656_979134.png
422
2-121109_756146.png
421
1-0170713_180413_516268.png
420
1-0170720_110218_926439.png
419
2-075705_737468.png
418
2-090059_059580.png
417
0-0018_038956.png
416
1-0170719_011951_407671.png
415
2-075243_065552.png
414
2-024631_875841.png
413
2-092558_511601.png
41

130
2-075305_378078.png
129
2-075740_109320.png
128
2-202005_784138.png
127
0-4614_586988.png
126
2-202020_939675.png
125
1-0170718_130304_749223.png
124
1-0170716_050829_416550.png
123
1-0170718_113346_897861.png
122
2-024629_313502.png
121
0-0152_462881.png
120
2-015640_723029.png
119
0-0233_455333.png
118
1-0170718_130252_369276.png
117
2-095924_907294.png
116
0-0206_460952.png
115
2-075313_001120.png
114
2-075802_232536.png
113
1-0170716_045901_584096.png
112
0-0624_946270.png
111
1-0170713_081856_326451.png
110
2-115811_795896.png
109
0-0204_394642.png
108
1-0170716_035414_434556.png
107
2-040242_646847.png
106
2-074028_025155.png
105
2-193518_866551.png
104
1-0170713_170618_126653.png
103
2-075259_938873.png
102
1-0170713_090431_231742.png
101
2-121145_045390.png
100
0-1412_308485.png
99
0-5913_951510.png
98
0-0007_742154.png
97
2-075824_108886.png
96
0-0611_681032.png
95
2-193540_520224.png
94
2-090213_679314.png
93
2-193544_321288.png
92
2-161222_150477.png
91
1-0170718_193521_

In [285]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

d = np.vstack((a, b))
 

In [286]:
c = np.array([4,4,4])

In [287]:
np.vstack((d, c))

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 4]])

In [288]:
train_data_test = train_data_test/255.0

In [289]:
print(train_data_test)

[[ 0.00279892  0.00222991  0.00239908 ...,  0.0013687   0.00133795
   0.00146098]
 [ 0.00273741  0.00215302  0.00246059 ...,  0.00139946  0.00133795
   0.00143022]]


In [ ]:
train_img = np.array([], dtype="float32")
`

In [334]:
# ont-hot label 만들기
(labels, filenames) = return_all_filename("tmp")
idx = len(labels)

for i in range(idx):
    labels[i] = int(labels[i])

def _change_one_hot_label(idx):
    T = np.zeros((idx, 3))
    for index, row in enumerate(T):
        row[labels[index]] = 1

    return T
tmp = _change_one_hot_label(idx)
print(tmp)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [327]:
(labels, filenames) = return_all_filename("tmp")
idx = len(labels)
print(idx)
print(filenames)
print(labels[0])
print(labels[1])
print(labels[2])
print(labels[3])
print(labels[4])
print(labels[5])
print(labels[6])

6
['0-0156_394341.png', '1-0170713_080302_209800.png', '1-0170720_115840_457106.png', '1-0170720_134431_691415.png', '1-0170720_195709_027806.png', '2-005058_212568.png']
0
1
1
1
1
2


IndexError: list index out of range

In [317]:
(labels, filenames) = return_all_filename("train")
print(labels)
idx = len(labels)
for i in range(idx):
    labels[i] = int(labels[i])
print(labels)

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',

In [349]:
print(type(labels[random.randrange(0, len(filenames))]))

<class 'int'>
