In [4]:
import pickle

In [5]:
def Load_Dataset_X(dir_path, time_unit, window_size, gap, margin_rate):
    key_name_X = "X_" + \
                    str(time_unit) + "_" + \
                    str(window_size) + "_" + \
                    str(gap) + "_" + \
                    str(margin_rate)
                    

    with open(dir_path + key_name_X + ".pickle", 'rb') as handle:
        b_x = pickle.load(handle)
    return b_x
    
def Load_Dataset_y(dir_path, time_unit, window_size, gap, margin_rate):
    key_name_y = "y_" + \
                    str(time_unit) + "_" + \
                    str(window_size) + "_" + \
                    str(gap) + "_" + \
                    str(margin_rate)
                    

    with open(dir_path + key_name_y + ".pickle", 'rb') as handle:
        b_y = pickle.load(handle)
    return b_y

In [6]:
dataset_dir_path_tuple_type = "./dataset_pickle_tuple_type/"

key_name_X = "X_10_10_1_0.1.pickle"
key_name_y = "y_10_10_1_0.1.pickle"
pickle_load_dir_path = dataset_dir_path_tuple_type
idx_time_unit = 10
idx_window_size = 10
idx_gap = 1
idx_margix_rate = 0.1

X = Load_Dataset_X(pickle_load_dir_path, idx_time_unit, idx_window_size, idx_gap, idx_margix_rate)
y = Load_Dataset_y(pickle_load_dir_path, idx_time_unit, idx_window_size, idx_gap, idx_margix_rate)

In [7]:
X

array([[[[1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         ...,
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00]],

        [[9.86945722e-01, 9.90486761e-01, 9.84356007e-01,
          6.57925102e+01],
         [9.92072301e-01, 9.92547963e-01, 9.85730141e-01,
          1.50588363e+02],
         [9.88848370e-01, 9.92230855e-01, 9.88319856e-01,
          9.22469100e+01],
         ...,
         [1.00475662e+00, 1.01210295e+00, 9.97304582e-01,
          3.17738502e+02],
         [1.01051741e+00, 1.01759949e+00, 1.00417526e+00,
          3.83238522e+02],
         [1.00000000e+00, 1.0135299

In [8]:
y

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 1, 1]])

In [9]:
X.shape

(52133, 8, 10, 4)

In [10]:
type(X)

numpy.ndarray

In [11]:
X[-1]

array([[[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00]],

       [[9.93071594e-01, 9.98818411e-01, 9.91943713e-01, 6.45446605e+01],
        [9.98442451e-01, 9.98872120e-01, 9.91460336e-01, 7.78684904e+01],
        [9.92695633e-01, 9.98442451e-01, 9.88828616e-01, 6.35570329e+01],
        [9.93877222e-01, 9.94414308e