# Numpy

In [2]:
! python --version

Python 3.6.5 :: Anaconda, Inc.


In [1]:
import numpy as np

## # numpy 생성

### - numpy.ndarray 생성
> np.array(파이썬 리스트)

#### 1-demension array

In [7]:
x_list = [1.0, 2.0, 3.0]
print(x_list)
print(type(x_list), end="\n\n")
x_np = np.array(x_list)
print(x_np)
print(type(x_np), end="\n\n")

[1.0, 2.0, 3.0]
<class 'list'>

[1. 2. 3.]
<class 'numpy.ndarray'>



#### 2-demension array

In [27]:
x_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("x_2d:\n{}".format(x_2d), end="\n\n")
print("x_2d.shape: {}".format(x_2d.shape))
print(type(x_2d), end="\n\n")

x_2d:
[[1 2 3]
 [4 5 6]]

x_2d.shape: (2, 3)
<class 'numpy.ndarray'>



### - identity matrix 생성
> np.eye(number)

- 2-D array 반환
- 대각성분:1, 대각성분 이외의 성분:0

In [3]:
eye = np.eye(4)
print("{}".format(eye))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### # numpy 산술연산
- element-wise 연산

In [23]:
x_a = np.array([1, 2, 3])
print("x_a: ", x_a)
x_b = np.array([1, 2, 3])
print("x_a: ", x_b)
print()

print("x_a + x_b: ", x_a+x_b)
print("x_a - x_b: ", x_a-x_b)
print("x_a * x_b: ", x_a*x_b)
print("x_a / x_b: ", x_a/x_b) # defualt float

x_a:  [1 2 3]
x_a:  [1 2 3]

x_a + x_b:  [2 4 6]
x_a - x_b:  [0 0 0]
x_a * x_b:  [1 4 9]
x_a / x_b:  [1. 1. 1.]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
