# Scipy

In [2]:
! python --version

Python 3.6.5 :: Anaconda, Inc.


In [8]:
from scipy import sparse
import numpy as np

In [9]:
# 항등행렬 생성 후, 0이 아닌 원소 추출
eye = np.eye(4)
print("{}".format(eye), end="\n\n")
sparse_matrix = sparse.csr_matrix(eye)
print("SciPy sparse CSR matrix:\n{}".format(sparse_matrix))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [10]:
# 임의의 행렬 생성 후, 0이 아닌 원소 추출
x_2d = np.array([[1, 0, 3], [4, 0, 0]])
print("{}".format(x_2d), end="\n\n")
sparse_matrix = sparse.csr_matrix(x_2d)
print("SciPy sparse CSR matrix:\n{}".format(sparse_matrix))

[[1 0 3]
 [4 0 0]]

SciPy sparse CSR matrix:
  (0, 0)	1
  (0, 2)	3
  (1, 0)	4
