# Scipy

## # version check

In [16]:
import scipy as sp
print("SciPy version: {}".format(sp.__version__))

SciPy version: 1.1.0


In [8]:
from scipy import sparse
import numpy as np

### # Sparse Matrix

#### - 항등행렬 생성 후, 0이 아닌 원소 추출

In [14]:
eye = np.eye(4)
print("{}".format(eye), end="\n\n")
sparse_matrix = sparse.csr_matrix(eye)
print("SciPy sparse CSR matrix:\n{}".format(sparse_matrix))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


#### - 임의의 행렬 생성 후, 0이 아닌 원소 추출

In [11]:
x_2d = np.array([[1, 0, 3], [4, 0, 0]])
print("{}".format(x_2d), end="\n\n")
sparse_matrix = sparse.csr_matrix(x_2d)
print("SciPy sparse CSR matrix:\n{}".format(sparse_matrix))
print("sparse_matrix.data: ", sparse_matrix.data)
print("sparse_matrix.get_shape: ", sparse_matrix.get_shape())
print("type(sparse_matrix.get_shape: ", type(sparse_matrix.get_shape()))

[[1 0 3]
 [4 0 0]]

SciPy sparse CSR matrix:
  (0, 0)	1
  (0, 2)	3
  (1, 0)	4
sparse_matrix.data:  [1 3 4]
sparse_matrix.get_shape:  (2, 3)
type(sparse_matrix.get_shape:  <class 'tuple'>


##### * CSR?
  - Compressed sparse row
  - 행의 인덱스를 압축하여 저장하는 방식
  <img src="./image/2D55FA3A-650D-4510-9F97-7FF1E6DA01C3.png"></img>
  
  <img src="./image/41CC3C75-0B5F-44CE-A805-4D58EA4D2CBF.png"></img>

#### - Convert Numpy array to Sparse Matrix in Coordinate(coo) format

In [15]:
data = np.ones(5) * -10
print("data:\n{}".format(data))

row_indices = np.arange(5)
print("row_indices:\n{}".format(row_indices))

col_indices = np.arange(5)
print("col_indices:\n{}".format(col_indices))

eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO representation:\n{}".format(eye_coo))

data:
[-10. -10. -10. -10. -10.]
row_indices:
[0 1 2 3 4]
col_indices:
[0 1 2 3 4]
COO representation:
  (0, 0)	-10.0
  (1, 1)	-10.0
  (2, 2)	-10.0
  (3, 3)	-10.0
  (4, 4)	-10.0
