In [1]:
! pwd

/Users/dohyung/SourceTree/dohyung/5.RNN


In [2]:
import pandas as pd
coin_data = pd.read_pickle('../_dataset/RNN_coin/X_10_10_1_0.1.pickle')

In [5]:
coin_data

(array([[[[1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
           1.00000000e+00],
          [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
           1.00000000e+00],
          [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
           1.00000000e+00],
          ...,
          [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
           1.00000000e+00],
          [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
           1.00000000e+00],
          [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
           1.00000000e+00]],
 
         [[9.91535206e-01, 9.96344748e-01, 9.91342824e-01,
           1.39001852e+02],
          [9.91919969e-01, 9.93459023e-01, 9.89803771e-01,
           1.47394685e+02],
          [9.93266641e-01, 9.94036168e-01, 9.90958061e-01,
           7.57722642e+01],
          ...,
          [9.98653328e-01, 9.99422855e-01, 9.95959985e-01,
           6.90474800e+01],
          [1.00000000e+00, 1.00019238e+00, 9.95959985e-01,
           1.24198021e+02],
          

In [10]:
import numpy as np
coin_data_x_np = np.array(coin_data[0])

In [11]:
coin_data_y_np = np.array(coin_data[0])

In [12]:
coin_data_x_np

array([[[[1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         ...,
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00]],

        [[9.91535206e-01, 9.96344748e-01, 9.91342824e-01,
          1.39001852e+02],
         [9.91919969e-01, 9.93459023e-01, 9.89803771e-01,
          1.47394685e+02],
         [9.93266641e-01, 9.94036168e-01, 9.90958061e-01,
          7.57722642e+01],
         ...,
         [9.98653328e-01, 9.99422855e-01, 9.95959985e-01,
          6.90474800e+01],
         [1.00000000e+00, 1.00019238e+00, 9.95959985e-01,
          1.24198021e+02],
         [1.00000000e+00, 1.0001923

In [13]:
coin_data_y_np

array([[[[1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         ...,
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00],
         [1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
          1.00000000e+00]],

        [[9.91535206e-01, 9.96344748e-01, 9.91342824e-01,
          1.39001852e+02],
         [9.91919969e-01, 9.93459023e-01, 9.89803771e-01,
          1.47394685e+02],
         [9.93266641e-01, 9.94036168e-01, 9.90958061e-01,
          7.57722642e+01],
         ...,
         [9.98653328e-01, 9.99422855e-01, 9.95959985e-01,
          6.90474800e+01],
         [1.00000000e+00, 1.00019238e+00, 9.95959985e-01,
          1.24198021e+02],
         [1.00000000e+00, 1.0001923

In [21]:
coin_data_y_np.shape

(52550, 8, 10, 4)

In [22]:
coin_data_x_np_reshaped = coin_data_x_np.reshape(52550*8, -1)

In [23]:
coin_data_x_np_reshaped.shape

(420400, 40)

In [24]:
coin_data_x_pd = pd.DataFrame(coin_data_x_np_reshaped)

In [17]:
len(coin_data[0][0][0])

10

In [19]:
len(coin_data[1])

52550