# Numpy

## # version check

In [12]:
import numpy as np
print("NumPy version: {}".format(np.__version__))

NumPy version: 1.14.5


## # numpy 생성

### - numpy.ndarray 생성
> <code>np.array(파이썬 리스트)</code>

#### 1-demension array

In [7]:
x_list = [1.0, 2.0, 3.0]
print(x_list)
print(type(x_list), end="\n\n")
x_np = np.array(x_list)
print(x_np)
print(type(x_np), end="\n\n")

[1.0, 2.0, 3.0]
<class 'list'>

[1. 2. 3.]
<class 'numpy.ndarray'>



#### 2-demension array

In [27]:
x_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("x_2d:\n{}".format(x_2d), end="\n\n")
print("x_2d.shape: {}".format(x_2d.shape))
print(type(x_2d), end="\n\n")

x_2d:
[[1 2 3]
 [4 5 6]]

x_2d.shape: (2, 3)
<class 'numpy.ndarray'>



### - identity matrix 생성
> <code>np.eye(number)</code>

- 2-D array 반환
- 대각성분:1, 대각성분 이외의 성분:0

In [3]:
eye = np.eye(4)
print("{}".format(eye))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### - np.ones(number)

In [6]:
data = np.ones(5)
print("data:\n{}".format(data))
data = np.ones(5) * -10
print("data:\n{}".format(data))

data:
[1. 1. 1. 1. 1.]
data:
[-10. -10. -10. -10. -10.]


### - np.arange(number)

In [9]:
row_indices = np.arange(5)
print("row_indices:\n{}".format(row_indices))

row_indices:
[0 1 2 3 4]


### - a에서 b까지 일정한 간격의 N개의 배열 생성
> <code>np.linspace(a, b, N)</code>

In [10]:
linspace = np.linspace(-10, 10, 100)
print("linspace:\n{}".format(linspace))

linspace:
[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
 

### - 삼각함수
> <code>np.sin( numpy.ndarray )</code>

In [11]:
linspace = np.linspace(-10, 10, 100)
sin = np.sin(linspace)
print("sin:\n{}".format(sin))

sin:
[ 0.54402111  0.36459873  0.17034683 -0.03083368 -0.23076008 -0.42130064
 -0.59470541 -0.74392141 -0.86287948 -0.94674118 -0.99209556 -0.99709789
 -0.96154471 -0.8868821  -0.77614685 -0.63384295 -0.46575841 -0.27872982
 -0.0803643   0.12126992  0.31797166  0.50174037  0.66510151  0.80141062
  0.90512352  0.97202182  0.99938456  0.98609877  0.93270486  0.84137452
  0.7158225   0.56115544  0.38366419  0.19056796 -0.01027934 -0.21070855
 -0.40256749 -0.57805259 -0.73002623 -0.85230712 -0.93992165 -0.98930624
 -0.99845223 -0.96698762 -0.8961922  -0.78894546 -0.64960951 -0.48385164
 -0.2984138  -0.10083842  0.10083842  0.2984138   0.48385164  0.64960951
  0.78894546  0.8961922   0.96698762  0.99845223  0.98930624  0.93992165
  0.85230712  0.73002623  0.57805259  0.40256749  0.21070855  0.01027934
 -0.19056796 -0.38366419 -0.56115544 -0.7158225  -0.84137452 -0.93270486
 -0.98609877 -0.99938456 -0.97202182 -0.90512352 -0.80141062 -0.66510151
 -0.50174037 -0.31797166 -0.12126992  0.080364

### # numpy 산술연산
- element-wise 연산

In [23]:
x_a = np.array([1, 2, 3])
print("x_a: ", x_a)
x_b = np.array([1, 2, 3])
print("x_a: ", x_b)
print()

print("x_a + x_b: ", x_a+x_b)
print("x_a - x_b: ", x_a-x_b)
print("x_a * x_b: ", x_a*x_b)
print("x_a / x_b: ", x_a/x_b) # defualt float

x_a:  [1 2 3]
x_a:  [1 2 3]

x_a + x_b:  [2 4 6]
x_a - x_b:  [0 0 0]
x_a * x_b:  [1 4 9]
x_a / x_b:  [1. 1. 1.]
